Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
    config.vm.provider :virtualbox do |vbox|
      vbox.gui = false
      vbox.name = "deepce"
    end
  
  config.vm.hostname = "deepce"
  
  config.vm.provision :shell, :inline => "sudo apt update"
  config.vm.provision :shell, :inline => "sudo apt install -y zip nmap aha"
  
  config.vm.provision "shell", keep_color: true, name: "docker.sh", path: "scripts/docker.sh"
  
  config.vm.provision :shell, :inline => "echo ubuntu:ubuntu | sudo chpasswd"
  config.vm.provision :shell, :inline => "echo root:iamroot| sudo chpasswd" # Give them something to crack if they want
  config.vm.provision :shell, :inline => "sudo usermod -aG docker ubuntu"
  
  # Add alias
  config.vm.provision :shell, :inline => "echo alias deepce='/opt/deepce/deepce.sh'>> /home/ubuntu/.bashrc"
  
  # enable ssh
  config.vm.provision :shell, :inline => "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && sudo service sshd restart"
  
  # Add deepce
  config.vm.provision :shell, :inline => "sudo git clone https://github.com/stealthcopter/deepce /opt/deepce && sudo chown -R ubuntu:ubuntu /opt/deepce"
  config.vm.provision :shell, :inline => "sudo zip -r /opt/deepce.zip /opt/deepce"
  
  # Add linpeas
  config.vm.provision :shell, :inline => "cd /opt && sudo wget https://raw.githubusercontent.com/carlospolop/privilege-escalation-awesome-scripts-suite/master/linPEAS/linpeas.sh && chmod a+rx /opt/linpeas.sh"
  
  # Run all tests so that all docker images are pulled down
  config.vm.provision :shell, :inline => "cd /opt/deepce/tests && ./run-all.sh || echo some tests failed, but lets carry on..."
  
  # Symlinks to apps
  config.vm.provision :shell, :inline => "ln -s /opt/deepce /home/ubuntu/deepce"
  
  # Copy files to home dir
  config.vm.provision "file", source: "home", destination: "/tmp/home"
  config.vm.provision "shell",inline: "chown -R ubuntu:ubuntu /tmp/home && mv /tmp/home/* /home/ubuntu/"
end

# TODO
# - Install metasploit & modules
