Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.name = "deepce"
  config.vm.hostname = "deepce"
  
  config.vm.provision :shell, :inline => "sudo apt update"
  config.vm.provision :shell, :inline => "sudo apt install docker.io zip"
  config.vm.provision :shell, :inline => "echo ubuntu:ubuntu | sudo chpasswd"
  config.vm.provision :shell, :inline => "sudo usermod -aG docker ubuntu"
  config.vm.provision :shell, :inline => "sudo git clone https://github.com/stealthcopter/deepce /opt/deepce && sudo chown -R ubuntu:ubuntu /opt/deepce"
  config.vm.provision :shell, :inline => "sudo zip -r /opt/deepce /opt/deepce.zip"
  
  
end
